### ISSUE TITLE
What is the relation with https://github.com/butzist/ProGraphMSA?

### ISSUE THREAD

**Issue by richelbilderbeek** [acg-team/ProGraphMSA#5]
ProGraphMSA looks awesome to me!

I notice there are two similar repos:

 * [https://github.com/butzist/ProGraphMSA](https://github.com/butzist/ProGraphMSA)
 * [https://github.com/acg-team/ProGraphMSA](https://github.com/acg-team/ProGraphMSA)

To avoid confusion, I suggest to add to the README.md the relation between these two repos.

In that way, others and I can decide which to base our future research on.

**Comment by sbliven** [comment]
@butzist was the original author of ProGraphMSA. His version seems to be a backup fork of the sourceforge tarball (which this repo also started with). This fork should be considered the current version, as it is available to all members of the Anisimova group and includes some minor improvements that I made during my postdoc with her.

**Comment by sbliven** [comment]
I've added branch [butzist](https://github.com/acg-team/ProGraphMSA/tree/butzist) to explicitly connect the two repos. The [comparison](https://github.com/acg-team/ProGraphMSA/compare/v2013-07-09...acg-team:butzist) makes clear that this repo derives from @butzist's code.

I've also documented the history in the README of this repo.

**Comment by richelbilderbeek** [comment]
Thanks @sbliven for clearing this up :+1:
